"""MkDocs macros for running tracking.

Reads the local data file `docs/notes/health/data/running.yml` (generated by
`uv run poe sync-running` from the deployed running_page site) — no network
access at build/serve time. If the data file is missing, every macro renders a
friendly hint instead of failing.
"""

import os
from datetime import datetime, timedelta
from typing import Any

import yaml

_DATA_PATH = os.path.join("notes", "health", "data", "running.yml")

_MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def _load_data(env: Any) -> dict:
    """Load running.yml relative to the docs directory."""
    docs_dir = env.conf.get("docs_dir", "docs")
    data_path = os.path.join(docs_dir, _DATA_PATH)
    if not os.path.exists(data_path):
        return {}
    with open(data_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    # empty/comment-only file -> None; non-dict top level (hand-edited) -> {}
    return data if isinstance(data, dict) else {}


def _no_data() -> str:
    """Friendly hint rendered when the data file is missing."""
    return "> ⚠️ No running data yet — run `uv run poe sync-running` to fetch it."


def _parse_moving_time(interval: Any) -> float | None:
    """Parse running_page interval ('0:19:42.196000') to seconds."""
    if not interval:
        return None
    try:
        parts = [float(p) for p in str(interval).split(":")]
    except ValueError:
        return None
    sec = 0.0
    for p in parts:
        sec = sec * 60 + p
    return sec


def _fmt_hours_minutes(seconds: float) -> str:
    """Format seconds as 'Xh Ym' (e.g. '12h 34m')."""
    total = int(round(seconds))
    h, rem = divmod(total, 3600)
    m = rem // 60
    if h:
        return f"{h}h {m}m"
    return f"{m}m"


def _fmt_pace(sec_per_km: float) -> str:
    """Format seconds/km as 'M:SS' (e.g. '5:32'), or '—' when absent."""
    if sec_per_km is None or sec_per_km <= 0:
        return "—"
    total = int(round(sec_per_km))
    m, s = divmod(total, 60)
    return f"{m}:{s:02d}"


def _activity_date(activity: dict) -> datetime | None:
    """Local activity timestamp (falls back to UTC start_date).

    If the primary field (start_date_local) exists but is unparseable, try the
    secondary field (start_date) before giving up.
    """
    candidates = [
        activity.get("start_date_local"),
        activity.get("start_date"),
    ]
    for raw in candidates:
        if not raw:
            continue
        try:
            return datetime.strptime(str(raw), "%Y-%m-%d %H:%M:%S")
        except ValueError:
            continue
    return None


def _runs(data: dict) -> list[dict]:
    """Activities (already filtered to Run), newest first.

    Upstream order is oldest-first; sort defensively so callers can rely on
    runs[0] being the most recent activity.
    """
    runs = list(data.get("activities") or [])

    def _sort_key(a: dict) -> datetime:
        return _activity_date(a) or datetime.min  # unparseable dates sort oldest

    return sorted(runs, key=_sort_key, reverse=True)


# ---------------------------------------------------------------------------
#  Summary cards
# ---------------------------------------------------------------------------


def _summary(data: dict) -> str:
    runs = _runs(data)
    if not runs:
        return _no_data()

    n = len(runs)
    total_km = sum(float(a.get("distance") or 0) for a in runs) / 1000.0
    total_sec = sum(_parse_moving_time(a.get("moving_time")) or 0 for a in runs)
    total_elev = sum(float(a.get("elevation_gain") or 0) for a in runs)
    hrs = [float(a.get("average_heartrate")) for a in runs if a.get("average_heartrate")]
    avg_hr = (sum(hrs) / len(hrs)) if hrs else None

    cards = [
        ("Runs", f"{n}"),
        ("Distance", f"{total_km:.1f} km"),
        ("Total Time", _fmt_hours_minutes(total_sec)),
        ("Elevation", f"{total_elev:.0f} m"),
        ("Avg HR", f"{avg_hr:.0f} bpm" if avg_hr else "—"),
    ]
    parts = ['<div class="weight-cards">\n']
    for label, value in cards:
        parts.append(
            f'    <div class="weight-card">'
            f'<div class="label">{label}</div>'
            f'<div class="value">{value}</div>'
            f"</div>\n"
        )
    parts.append("</div>\n")
    return "".join(parts)


# ---------------------------------------------------------------------------
#  Yearly table
# ---------------------------------------------------------------------------


def _year_table(data: dict) -> str:
    runs = _runs(data)
    if not runs:
        return _no_data()

    years: dict[int, dict] = {}
    for a in runs:
        dt = _activity_date(a)
        if dt is None:
            continue
        y = years.setdefault(dt.year, {"n": 0, "km": 0.0, "sec": 0.0, "elev": 0.0, "hrs": []})
        y["n"] += 1
        y["km"] += float(a.get("distance") or 0) / 1000.0
        y["sec"] += _parse_moving_time(a.get("moving_time")) or 0
        y["elev"] += float(a.get("elevation_gain") or 0)
        if a.get("average_heartrate"):
            y["hrs"].append(float(a["average_heartrate"]))

    md = "| Year | Runs | Distance (km) | Avg Pace | Avg HR | Elevation (m) |\n"
    md += "|:-----|-----:|--------------:|:--------:|-------:|--------------:|\n"
    for year in sorted(years, reverse=True):
        y = years[year]
        pace = _fmt_pace(y["sec"] / y["km"]) if y["km"] else "—"
        hr = f"{sum(y['hrs']) / len(y['hrs']):.0f}" if y["hrs"] else "—"
        md += f"| {year} | {y['n']} | {y['km']:.1f} | {pace} | {hr} | {y['elev']:.0f} |\n"
    return md


# ---------------------------------------------------------------------------
#  Monthly chart (Mermaid) — distance bar + avg HR line, merged on one plot
# ---------------------------------------------------------------------------


def _monthly_chart(data: dict) -> str:
    """Merged bar (km) + line (bpm) chart for the latest activity year.

    xychart-beta has a single y-axis and does not accept null values (v10.9),
    so the x-axis covers only months with activities — every bar/line slot
    then has a real value.
    """
    runs = _runs(data)
    if not runs:
        return _no_data()

    latest = _activity_date(runs[0])
    if latest is None:
        return _no_data()
    year = latest.year

    months: dict[int, dict] = {}
    for a in runs:
        dt = _activity_date(a)
        if dt is None or dt.year != year:
            continue
        m = months.setdefault(dt.month, {"km": 0.0, "hrs": []})
        m["km"] += float(a.get("distance") or 0) / 1000.0
        if a.get("average_heartrate"):
            m["hrs"].append(float(a["average_heartrate"]))

    if not months:
        return f"> No runs in {year} yet"

    ordered = sorted(months)
    labels = ", ".join(f'"{_MONTHS[m - 1]}"' for m in ordered)
    bars = ", ".join(f"{months[m]['km']:.1f}" for m in ordered)
    # every activity today carries HR, so the 0 fallback is defensive only:
    # mermaid 10.9 xychart rejects null values, so the month shows as 0
    lines = ", ".join(
        f"{sum(months[m]['hrs']) / len(months[m]['hrs']):.0f}" if months[m]["hrs"] else "0"
        for m in ordered
    )
    km_max = max(months[m]["km"] for m in ordered)
    hr_max = max(
        (sum(months[m]["hrs"]) / len(months[m]["hrs"]) for m in ordered if months[m]["hrs"]),
        default=0,
    )
    y_max = int((max(km_max, hr_max + 10) // 5 + 1) * 5)

    return (
        "```mermaid\n"
        "xychart-beta\n"
        f'    title "Monthly Distance (km) & Avg HR (bpm) — {year}"\n'
        f"    x-axis [{labels}]\n"
        f'    y-axis "km / bpm" 0 --> {y_max}\n'
        f"    bar [{bars}]\n"
        f"    line [{lines}]\n"
        "```"
    )


# ---------------------------------------------------------------------------
#  Activity tables (recent / all) — shared header + rows, newest first
# ---------------------------------------------------------------------------


def _activity_table(runs: list[dict]) -> str:
    """Markdown table (header + rows) for the given activities.

    Date / Time / Duration are merged into a single column to keep the table
    narrow; a note above the header explains the abbreviations.
    """
    md = "> Avg HR = Average Heart Rate（平均心率）｜ Pace (/km) = 每公里配速（min/km）\n\n"
    md += "| Date · Time · Duration | Name | Distance (km) | Pace (/km) | Avg HR |\n"
    md += "|:------------------------|:-----|--------------:|:----------:|-------:|\n"
    for a in runs:
        dt = _activity_date(a)
        sec = _parse_moving_time(a.get("moving_time"))
        dur = _fmt_hours_minutes(sec) if sec else "—"
        when_dur = f"{dt.strftime('%Y-%m-%d %H:%M')} · {dur}" if dt else "—"
        # escape pipe/newline so activity names can't break the Markdown table
        name = str(a.get("name") or "—").replace("|", "\\|").replace("\n", " ")
        km = float(a.get("distance") or 0) / 1000.0
        pace = _fmt_pace(sec / km) if sec and km else "—"
        hr = f"{float(a['average_heartrate']):.0f}" if a.get("average_heartrate") else "—"
        md += f"| {when_dur} | {name} | {km:.2f} | {pace} | {hr} |\n"
    return md


# ---------------------------------------------------------------------------
#  Recent activities table — last 2 weeks
# ---------------------------------------------------------------------------


def _recent(data: dict) -> str:
    runs = _runs(data)
    if not runs:
        return _no_data()

    # last 2 weeks; fall back to the last 10 activities when data is stale
    cutoff = datetime.now() - timedelta(days=14)
    two_weeks = [a for a in runs if (dt := _activity_date(a)) is not None and dt >= cutoff]
    rows = two_weeks if two_weeks else runs[:10]
    return _activity_table(rows)


# ---------------------------------------------------------------------------
#  All activities table — collapsed by default
# ---------------------------------------------------------------------------


def _all(data: dict) -> str:
    runs = _runs(data)
    if not runs:
        return _no_data()

    md = f'??? "🗂️ All Activities ({len(runs)})"\n'
    for line in _activity_table(runs).rstrip("\n").split("\n"):
        md += f"    {line}\n"
    return md


# ---------------------------------------------------------------------------
#  Sync note
# ---------------------------------------------------------------------------


def _synced_note(data: dict) -> str:
    synced_at = data.get("synced_at")
    if not synced_at:
        # never claim there is no data just because synced_at is missing
        # (only reachable via hand-edited files)
        return "> ⚠️ 未记录同步时间 — 运行 `uv run poe sync-running` 可更新数据。"
    return f"> 🕓 Data synced at `{synced_at}` — re-run `uv run poe sync-running` to refresh."


# ---------------------------------------------------------------------------
#  Public macros
# ---------------------------------------------------------------------------


def define_env(env):
    """Register running tracking macros."""

    @env.macro
    def running_summary():
        """Cards: total runs, distance, time, elevation, avg heart rate."""
        return _summary(_load_data(env))

    @env.macro
    def running_year_table():
        """Yearly stats: year, runs, distance, avg pace, avg HR, elevation."""
        return _year_table(_load_data(env))

    @env.macro
    def running_monthly_chart():
        """Merged Mermaid chart: monthly distance (bar) + avg heart rate (line)."""
        return _monthly_chart(_load_data(env))

    @env.macro
    def running_recent():
        """Table of activities from the last 2 weeks (fallback: last 10)."""
        return _recent(_load_data(env))

    @env.macro
    def running_all():
        """Collapsed table of all activities."""
        return _all(_load_data(env))

    @env.macro
    def running_synced_at():
        """Note showing when the local data was last synced."""
        return _synced_note(_load_data(env))
