# site settings
site_name: recycle.bin
site_url: https://xiongjia.github.io
site_author: xiongjia
site_description: recycle.bin
repo_name: recycle.bin
repo_url: https://github.com/xiongjia/xiongjia.github.com
copyright: Copyright &copy; 2025 - present <a href="https://github.com/xiongjia/xiongjia.github.com" target="_blank" rel="noopener noreferrer">recycle.bin</a>

# plugins
plugins:
  - minify: { minify_html: true }
  - search: { lang: js }
  - mermaid2
  - drawio
  - rss:
      enabled: true
      match_path: notes/posts/tests/.* 
      date_from_meta:
        as_creation: date
  - tags:
      tags_hierarchy: true
      listings_map:
        scoped:
          scope: true
  - blog: 
      blog_dir: notes
      blog_toc: true
      pagination_if_single_page: true
      pagination_per_page: 5
      pagination_url_format: "{page}"
      pagination_keep_content: false


# theme setting
theme:
  name: material
  nav_style: light
  include_search_page: false
  search_index_only: true
  icon: { repo: fontawesome/brands/github }
  features:
    - header.autohide
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.prune
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

# Extensions settings
markdown_extensions:
  - attr_list

# Page tree
nav:
  - HOME: index.md
  - NOTES:
    - notes/index.md    
  - TECH:
    - Index: tech/index.md
    - Tech1: tech/tech1.md
