// Node unit tests for docs/notes/health/running-route-core.js (the pure
// helpers of the running page's route maps). Run with:
//     node tests/test_running_route_core.cjs
// or `uv run poe test-js`. Reference encoded strings below were generated by
// the Python reference encoder (scripts/sync_running.py `_encode_polyline`,
// which takes (lat, lng) pairs) — keep them in sync when the polyline
// contract changes.

const assert = require("node:assert");
const core = require("../docs/notes/health/running-route-core.js");

// Reference polyline strings from Python: [(lat, lng), ...]
const PY_SAMPLES = {
  shanghai: "_wl}D_nqdVo}@o}@o}@_|B",
  negative: "~vl}D~mqdVn}@n}@",
  two_point: "_qwyD_wh`Vo}@o}@",
};

// Independent encoder mirroring the Python reference ([(lat, lng), ...]).
// Uses Math.round (half-away-from-zero) while Python's round() is
// round-half-even — the PY_SAMPLES points are chosen to avoid values whose
// 1e5-scaled product ends in exactly .5, so the two agree. Add samples
// carefully if this ever grows.
function encodeLatLng(points) {
  let out = "";
  let latPrev = 0, lngPrev = 0;
  const enc = (val) => {
    let sval = val < 0 ? ~(val << 1) : val << 1;
    let chunk = "";
    for (;;) {
      let b = sval & 0x1f;
      sval >>= 5;
      if (sval) b |= 0x20;
      chunk += String.fromCharCode(b + 63);
      if (!sval) break;
    }
    return chunk;
  };
  for (const [lat, lng] of points) {
    const lat5 = Math.round(lat * 1e5);
    const lng5 = Math.round(lng * 1e5);
    out += enc(lat5 - latPrev) + enc(lng5 - lngPrev);
    latPrev = lat5;
    lngPrev = lng5;
  }
  return out;
}

// Expected decoded coordinates ([lng, lat], degrees) for the Python reference
// strings — pins coordinate order and the 1e5 scaling, not just the bit
// encoding.
const EXPECTED = {
  shanghai: [[121.5, 31.2], [121.51, 31.21], [121.53, 31.22]],
  negative: [[-121.5, -31.2], [-121.51, -31.21]],
  two_point: [[120.8, 30.6], [120.81, 30.61]],
};

// ---- decodePolyline ----
for (const [name, enc] of Object.entries(PY_SAMPLES)) {
  assert.deepStrictEqual(
    core.decodePolyline(enc),
    EXPECTED[name],
    `${name}: absolute [lng, lat] degrees`
  );
}
// round-trip through the independent encoder (which is itself pinned to the
// Python reference below)
for (const pts of [
  [[31.2, 121.5], [31.21, 121.51], [31.22, 121.53]],
  [[-31.2, -121.5], [-31.21, -121.51]],
  [[0, 0], [0.00001, -0.00001]],
]) {
  const enc = encodeLatLng(pts);
  // decode returns degrees in [lng, lat] order (lat/lng swapped from input)
  assert.deepStrictEqual(
    core.decodePolyline(enc),
    pts.map(([lat, lng]) => [lng, lat]),
    "round-trip (lat,lng) -> [lng,lat]"
  );
}

// The JS encoder must reproduce the Python reference strings exactly — keeps
// the bit encoding and rounding in sync with scripts/sync_running.py.
assert.strictEqual(
  encodeLatLng([[31.2, 121.5], [31.21, 121.51], [31.22, 121.53]]),
  PY_SAMPLES.shanghai,
  "encoder matches Python reference"
);
assert.strictEqual(
  encodeLatLng([[-31.2, -121.5], [-31.21, -121.51]]),
  PY_SAMPLES.negative,
  "encoder matches Python reference (negative)"
);
assert.strictEqual(
  encodeLatLng([[30.6, 120.8], [30.61, 120.81]]),
  PY_SAMPLES.two_point,
  "encoder matches Python reference"
);

// ---- firstPolylinePoint ----
for (const [name, enc] of Object.entries(PY_SAMPLES)) {
  assert.deepStrictEqual(
    core.firstPolylinePoint(enc),
    EXPECTED[name][0],
    "first point matches the reference decode[0]"
  );
}
assert.strictEqual(core.firstPolylinePoint(null), null);
assert.strictEqual(core.firstPolylinePoint(""), null);
assert.throws(() => core.firstPolylinePoint("_wl}D"), /bad polyline/);

// ---- regionIndexFor ----
const regions = [[120.8, 30.6, 122.2, 31.8], [139.4, 35.4, 140.4, 36.4]];
assert.strictEqual(core.regionIndexFor([121.5, 31.2], regions), 0, "inside region 0");
assert.strictEqual(core.regionIndexFor([140.0, 36.0], regions), 1, "inside region 1");
assert.strictEqual(core.regionIndexFor([100.0, 20.0], regions), -1, "outside all");
assert.strictEqual(core.regionIndexFor([120.8, 30.6], regions), 0, "bbox edge is inclusive");
assert.strictEqual(core.regionIndexFor(null, regions), -1, "null point");
assert.strictEqual(core.regionIndexFor([121.5, 31.2], []), 0, "no regions = show all");
assert.strictEqual(core.regionIndexFor([121.5, 31.2], null), 0, "null regions = show all");

// ---- fmtClock ----
assert.strictEqual(core.fmtClock(332), "5:32");
assert.strictEqual(core.fmtClock(600), "10:00");
assert.strictEqual(core.fmtClock(3661), "61:01");
assert.strictEqual(core.fmtClock(0), "—");
assert.strictEqual(core.fmtClock(-5), "—");
assert.strictEqual(core.fmtClock(null), "—");

// ---- paceRowsFor ----
const rows = core.paceRowsFor({
  splits: [
    { km: 1.0, duration: 300, pace: "5:00", hr: 120 },
    { km: 0.4, duration: 90, pace: "3:45", hr: 130.4 },
    { km: 2.0 }, // missing duration/pace/hr
  ],
});
assert.deepStrictEqual(rows, [
  ["1", "5:00", "5:00", "120"],
  ["0.40", "1:30", "3:45", "130"],
  ["2", "—", "—", "—"],
]);
assert.deepStrictEqual(core.paceRowsFor({ splits: [] }), []);
assert.deepStrictEqual(core.paceRowsFor({}), []);

// ---- esc ----
assert.strictEqual(core.esc("a&b<c>d\"e'f"), "a&amp;b&lt;c&gt;d&quot;e&#39;f");
assert.strictEqual(core.esc("plain 123"), "plain 123");
assert.strictEqual(core.esc(42), "42");

console.log("running-route-core: all tests passed");
