version: 2

models:
  - name: stg_customers
    description: Standardized customers view
    columns:
      - name: customer_id
        tests: [unique, not_null]
      - name: email
        tests: [not_null]

  - name: stg_products
    description: Standardized products view
    columns:
      - name: product_id
        tests: [unique, not_null]

  - name: stg_orders
    description: Valid order headers view (cancelled removed)
    columns:
      - name: order_id
        tests: [unique, not_null]
      - name: customer_id
        tests: [not_null]

  - name: stg_order_items
    description: Order line items view (with line_total)
    columns:
      - name: item_id
        tests: [unique, not_null]
      - name: order_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]