name: Deploy MkDocs
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        
      - name: Install dependencies
        run: pdm install
        
      - name: Build and deploy
        run: |
          pdm run mkdocs gh-deploy --force 
